exports.cards = [
    { value: 'VOG', label: 'V.O.G', description:'Les V.O.G (VDN Olympic Games) ont une compétition où chaque participant des ateliers est invité à programmer un jeu ou une animation en 2D ou 3D sur le thème des jeux olympiques. Ceci peut être fait avec n’importe quel outil ou langage. Les valeurs sont Aider ses camarades, la Bienveillance et le Partage de savoir.', link:'https://vdngaite.github.io/projects/vog/index.html' },
    { value: 'Twine', label: 'Twine' , description:'Dans cet atelier, nous avons pris en main le logiciel Twine pour raconter des histoires à la façon d’un “livre dont vous être le héros” et s’initier à la pensée algorithmique.', link:'https://vdngaite.github.io/projects/twine/web/viewer.html?file=atelier_twine.pdf'},
    { value: 'Processing', label: 'Processing' , description:'Dans cet atelier, nous avons fait une initiation à la librairie javascript p5.js. On a crée une page html et ajouter différentes formes en 2D et 3D.', link:'https://vdngaite.github.io/projects/processing/index.html'},
    { value: 'Cross', label: 'Défi 1' , description:'Dans ce défi, nous allons dessiner une croix sur scratch. Comment feriez vous ?', link:'https://medium.com/@vdcgaite/d%C3%A9fi-1-la-croix-e0a71b18b4fc'},
    { value: 'Mochica', label: 'Mochica' , description:'Avec une artiste, nous avons collaboré pour créer un opéra électro numérique à la gaité lyrique', link:'https://medium.com/@vdcgaite/la-participation-dun-vdc-%C3%A0-la-cr%C3%A9ation-d-un-op%C3%A9ra-%C3%A9lectro-num%C3%A9rique-8454e2426da3'},
    { value: 'Futur', label: 'Futur en seine 2016' , description:'Réunissant plusieurs centaines d’exposants pour former le plus grand forum sur les nouvelles technologies d’Europe, Futur-en-Seine a accueilli les Voyageurs du Code.', link:'https://medium.com/@vdcgaite/a-futur-en-seine-%C3%A0-la-gait%C3%A9-lyrique-b74773b41841'},
    { value: 'Canope', label: 'Atelier à la Canopé' , description:'Le samedi 17 juin 2017 a eu lieu un atelier Voyageurs du Code avec les bénévoles de la Gaité Lyrique à la librairie Canopé à Paris.', link:'https://medium.com/@vdcgaite/retour-sur-latelier-des-vdc-de-la-gait%C3%A9-%C3%A0-la-librairie-canop%C3%A9-61e5c27d64e5'},
    { value: 'Casse-Brique', label: 'Fiche Casse Brique' , description:'Le but du jeu est très simple : il faut casser des briques ! Pour cela, il faut diriger une raquette et faire rebondir la balle dessus pour que celle-ci casse les briques présentes dans votre jeu.', link:'http://voyageursducode.fr/ressources/fiches-activites/casse-brique.html'},
    { value: 'Chasseur-de-zombies', label: 'Fiche Chasseur de zombies' , description:'Créer un jeu de tir où vous incarnez une héroïne qui combat les zombies. ', link:'http://voyageursducode.fr/ressources/fiches-activites/scratch-chasseur-de-zombies.html'}
];
